alias q='exit'
alias ls='ls -al --color=auto'
alias update='sudo apt update && sudo apt upgrade' 
alias src='source ~/.bashrc'
alias t='tree -h'
alias sus='systemctl suspend'
alias sd='systemctl poweroff'
alias rb='systemctl reboot'
alias stremio='flatpak run com.stremio.Stremio'
alias fd='fdfind'
alias i3c='vim ~/.config/i3/config'
alias v='vim'
# activate python virtual environment, gotta be in the root folder of the python project
alias venv='source venv/bin/activate'

# git
alias g="git"
alias gc="git checkout"
alias gco="git commit -am"
alias gps="git push"
alias gp="git pull"
alias gcm="git checkout main"
alias gpm="git pull origin main"
alias grh="git reset --hard"
alias gs="git status"
alias git_delete_merged='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'
